<a href="https://colab.research.google.com/github/Cs-Student/Deep_Learning_Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor(
    [[7,8],[9,10]]
    )

In [ ]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 1])

In [ ]:
matrix = torch.tensor(
    [[7],[9]]
    )

In [ ]:
matrix.shape


torch.Size([2, 1])

In [ ]:
matrix.ndim

2

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.9474, 0.9835, 0.0565, 0.9727],
        [0.6711, 0.2060, 0.1543, 0.1860],
        [0.4841, 0.0780, 0.2154, 0.4961]])

In [4]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6100, 0.2453, 0.4942, 0.9538],
         [0.9407, 0.0785, 0.7778, 0.5327],
         [0.5008, 0.6824, 0.6492, 0.3558]]])

In [5]:
random_tensor.shape

torch.Size([1, 3, 4])

In [6]:
random_tensor.ndim

3

In [10]:
random_tensor = torch.rand(size = (224, 224, 3))

In [8]:
random_tensor.ndim

3

In [9]:
random_tensor.shape

torch.Size([224, 224, 3])

In [11]:
random_tensor = torch.rand(224, 224, 3)
random_tensor.ndim, random_tensor.shape

(3, torch.Size([224, 224, 3]))

In [12]:
random_tensor = torch.rand(3, 224, 224)
random_tensor.ndim, random_tensor.shape

(3, torch.Size([3, 224, 224]))

In [16]:
random_tensor = torch.rand(size = (5, 5, 3))
random_tensor.ndim, random_tensor.shape, random_tensor

(3,
 torch.Size([5, 5, 3]),
 tensor([[[0.8460, 0.0789, 0.6250],
          [0.3079, 0.7113, 0.8092],
          [0.8997, 0.3107, 0.3330],
          [0.6028, 0.1744, 0.3252],
          [0.2232, 0.7778, 0.7058]],
 
         [[0.3456, 0.2846, 0.8155],
          [0.7953, 0.7096, 0.3118],
          [0.3591, 0.2566, 0.6556],
          [0.4425, 0.8309, 0.4047],
          [0.5015, 0.4213, 0.1028]],
 
         [[0.8897, 0.4689, 0.0567],
          [0.9974, 0.3538, 0.6544],
          [0.0320, 0.9792, 0.6968],
          [0.4515, 0.7529, 0.0634],
          [0.4438, 0.1382, 0.7228]],
 
         [[0.5611, 0.0565, 0.7518],
          [0.5771, 0.1854, 0.1115],
          [0.2954, 0.2818, 0.4122],
          [0.7547, 0.1114, 0.9312],
          [0.7100, 0.8936, 0.8872]],
 
         [[0.0283, 0.8557, 0.6988],
          [0.5226, 0.3278, 0.7208],
          [0.7027, 0.9093, 0.8686],
          [0.9299, 0.3115, 0.9422],
          [0.1405, 0.4581, 0.3870]]]))

In [18]:
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zero_to_ten = torch.range(0,10)
zero_to_ten

<ipython-input-19-aba71ad280e6>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
float_32_tensor = torch.rand(3,4)
float_32_tensor.device,float_32_tensor.dtype,float_32_tensor.shape

(device(type='cpu'), torch.float32, torch.Size([3, 4]))

In [32]:
tensor = torch.tensor([1,2,3])+10
tensor
#same for mulitplication/addition/division

tensor([11, 12, 13])

In [35]:
torch.tensor([1,2,3]) * torch.tensor([3,4,5])
#element wise multiplication

tensor([ 3,  8, 15])

In [4]:
#matmul is the most important maths operation we will be going to use

    # The inner dimensions must match:

    # (3, 2) @ (3, 2) won't work
    # (2, 3) @ (3, 2) will work
    # (3, 2) @ (2, 3) will work

    # The resulting matrix has the shape of the outer dimensions:

    # (2, 3) @ (3, 2) -> (2, 2)
    # (3, 2) @ (2, 3) -> (3, 3)

tensor = torch.tensor([1,3,4])
tensor @ tensor


tensor(26)

In [5]:
%%time
value = 0
for i in range(len(tensor)):
  value  += tensor[i] * tensor[i]
value

CPU times: user 1.6 ms, sys: 1.18 ms, total: 2.78 ms
Wall time: 16.4 ms


tensor(26)

In [6]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 184 µs, sys: 0 ns, total: 184 µs
Wall time: 190 µs


tensor(26)

In [15]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]], dtype = torch.float32)
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
print(output)

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [18]:
x = torch.rand([224,224,3])
x = x.permute(2,0,1)
x.shape

torch.Size([3, 224, 224])

In [19]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [20]:
x[0][1]

tensor([4, 5, 6])

In [22]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [23]:
#Exercise

In [25]:
tensor = torch.rand([7,7])
tensor.shape

torch.Size([7, 7])

In [29]:
tensor2 = torch.rand([1,7])
tensor @ tensor2.T

tensor([[1.4436],
        [1.9536],
        [2.2605],
        [1.6918],
        [1.9027],
        [1.5021],
        [2.2002]])